export default [
  {
    id: 'create_narrative',
    title: 'Create Narrative',
    meta: 'Start a new scenario',
    icon: 'plus',
    link: '/create-narrative',
  },
  {
    id: 'my_narratives',
    title: 'My Narratives',
    meta: 'A list of my creations',
    icon: 'write',
    link: '/my-narratives',
  },
  {
    id: 'joined_narratives',
    title: 'Joined Narratives',
    meta: 'A list of Narratives I joined',
    icon: 'conversation',
    link: '/joined-narratives',
  },
  {
    id: 'notifications',
    title: 'Notifications',
    meta: 'Updates on Narratives',
    icon: 'alarm',
    link: '/notifications',
  },
  {
    id: 'trophies',
    title: 'Trophies',
    meta: 'Gifted by fellow users',
    icon: 'trophy',
    link: '/trophies',
  },
  {
    id: 'settings',
    title: 'Settings',
    meta: 'Manage your account details',
    icon: 'setting',
    link: '/settings',
  },
  {
    id: 'logout',
    title: 'Log Out',
    meta: 'Keep your account safe in public',
    icon: 'sign out',
    link: '',
  },
];
