/*
 *
 * ScenePage constants
 *
 */

export const GET_SCENE_REQUEST = 'app/ScenePage/GET_SCENE_REQUEST';
export const GET_SCENE_SUCCESS = 'app/ScenePage/GET_SCENE_SUCCESS';
export const GET_SCENE_FAILURE = 'app/ScenePage/GET_SCENE_FAILURE';

export const GET_COMMENTS_REQUEST = 'app/ScenePage/GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'app/ScenePage/GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'app/ScenePage/GET_COMMENTS_FAILURE';

export const GET_MORE_COMMENTS_REQUEST = 'app/ScenePage/GET_MORE_COMMENTS_REQUEST';
export const GET_MORE_COMMENTS_SUCCESS = 'app/ScenePage/GET_MORE_COMMENTS_SUCCESS';
export const GET_MORE_COMMENTS_FAILURE = 'app/ScenePage/GET_MORE_COMMENTS_FAILURE';

export const POST_NARRATION_COMMENT_REQUEST = 'POST_NARRATION_COMMENT_REQUEST';
export const POST_NARRATION_COMMENT_SUCCESS = 'POST_NARRATION_COMMENT_SUCCESS';
export const POST_NARRATION_COMMENT_FAILURE = 'POST_NARRATION_COMMENT_FAILURE';

export const POST_DIALOGUE_COMMENT_REQUEST = 'POST_DIALOGUE_COMMENT_REQUEST';
export const POST_DIALOGUE_COMMENT_SUCCESS = 'POST_DIALOGUE_COMMENT_SUCCESS';
export const POST_DIALOGUE_COMMENT_FAILURE = 'POST_DIALOGUE_COMMENT_FAILURE';

export const SET_EDIT = 'app/ScenePage/SET_EDIT';
export const UNSET_EDIT = 'app/ScenePage/UNSET_EDIT';

export const UPDATE_COMMENT_REQUEST = 'app/ScenePage/UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'app/ScenePage/UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAILURE = 'app/ScenePage/UPDATE_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'app/ScenePage/DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'app/ScenePage/DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'app/ScenePage/DELETE_COMMENT_FAILURE';
